"""
Chat-related models: ChatSession.
"""

import uuid

from sqlalchemy import TIMESTAMP, Column, ForeignKey, String, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from .base import Base


class ChatSession(Base):
    __tablename__ = "chat_sessions"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # New fields for sidebar display
    title = Column(String(500), nullable=True)  # Generated summary/title
    agent_id = Column(
        UUID(as_uuid=True),
        ForeignKey("virtual_agents.id", ondelete="CASCADE"),
        nullable=True,
    )  # Agent ID
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )  # User ID for session isolation

    # LlamaStack conversation ID mapping
    conversation_id = Column(String(255), nullable=True)  # Auto-generated by LlamaStack

    created_at = Column(TIMESTAMP(timezone=True), server_default=func.now())
    updated_at = Column(
        TIMESTAMP(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )

    # Relationship to virtual agent
    agent = relationship("VirtualAgent")
