"""add_vector_store_ids_to_virtual_agent_configs

Revision ID: 0fcd68e18e68
Revises: 54358e0b69b8
Create Date: 2025-09-22 13:31:21.612229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fcd68e18e68'
down_revision: Union[str, None] = '54358e0b69b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_agent_configs', sa.Column('vector_store_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_agent_configs', 'vector_store_ids')
    # ### end Alembic commands ###
