"""change_agent_name_to_agent_id_foreign_key

Revision ID: 2b75adb4d75d
Revises: 4811a563909e
Create Date: 2025-09-26 12:51:18.262424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b75adb4d75d'
down_revision: Union[str, None] = '4811a563909e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('agent_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'virtual_agent_configs', ['agent_id'], ['id'])
    op.drop_column('chat_sessions', 'agent_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('agent_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'agent_id')
    # ### end Alembic commands ###
