"""updated chat session

Revision ID: 3b772ba5c9f9
Revises: ffa2dde7aae5
Create Date: 2025-06-03 14:33:20.394155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b772ba5c9f9'
down_revision: Union[str, None] = 'ffa2dde7aae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_history')
    op.add_column('chat_sessions', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('chat_sessions', sa.Column('agent_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'agent_name')
    op.drop_column('chat_sessions', 'title')
    op.create_table('chat_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('agent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_history_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_history_pkey')
    )
    # ### end Alembic commands ###
