"""initial_migration

Revision ID: 4c1617ab164c
Revises: 
Create Date: 2025-05-15 15:54:18.130721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1617ab164c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_assistant_tools', sa.Column('tool_id', sa.String(length=255), nullable=False))
    op.drop_column('virtual_assistant_tools', 'mcp_server_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_assistant_tools', sa.Column('mcp_server_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('virtual_assistant_tools', 'tool_id')
    # ### end Alembic commands ###
