"""add_vector_store_id_to_knowledge_bases

Revision ID: 54358e0b69b8
Revises: 5c60ebe607d9
Create Date: 2025-09-19 16:54:07.781925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54358e0b69b8'
down_revision: Union[str, None] = '5c60ebe607d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('vector_store_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'vector_store_id')
    # ### end Alembic commands ###
