"""rename vector_db_name to vector_store_name

Revision ID: 5c60ebe607d9
Revises: d52f80e39bc4
Create Date: 2025-09-19 12:25:55.293350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c60ebe607d9'
down_revision: Union[str, None] = 'd52f80e39bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_servers')
    op.drop_index(op.f('idx_agent_metadata_template'), table_name='agent_metadata')
    op.alter_column('agent_templates', 'description',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.drop_index(op.f('idx_agent_templates_suite'), table_name='agent_templates')
    # Rename column from vector_db_name to vector_store_name
    op.alter_column('knowledge_bases', 'vector_db_name', new_column_name='vector_store_name')
    op.alter_column('template_suites', 'description',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.drop_index(op.f('idx_template_suites_category'), table_name='template_suites')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_template_suites_category'), 'template_suites', ['category'], unique=False)
    op.alter_column('template_suites', 'description',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    # Rename column back from vector_store_name to vector_db_name
    op.alter_column('knowledge_bases', 'vector_store_name', new_column_name='vector_db_name')
    op.create_index(op.f('idx_agent_templates_suite'), 'agent_templates', ['suite_id'], unique=False)
    op.alter_column('agent_templates', 'description',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.create_index(op.f('idx_agent_metadata_template'), 'agent_metadata', ['template_id'], unique=False)
    op.create_table('model_servers',
                    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('provider_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('model_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('endpoint_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('model_servers_pkey'))
                    )
    # ### end Alembic commands ###
