"""removed_tooltype

Revision ID: 7fc140ef6ec7
Revises: 8d733567d021
Create Date: 2025-05-28 13:26:50.073295

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7fc140ef6ec7"
down_revision: Union[str, None] = "8d733567d021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("virtual_assistant_tools", "tool_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "virtual_assistant_tools",
        sa.Column(
            "tool_type",
            postgresql.ENUM("BUILTIN", "MCP_SERVER", name="tool_type_enum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
