"""Add conversation_id and remove session_state from chat_sessions

Revision ID: 8b71c25a7317
Revises: 842ca8450e9f
Create Date: 2025-11-10 12:19:19.087474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b71c25a7317'
down_revision: Union[str, None] = '842ca8450e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('conversation_id', sa.String(length=255), nullable=True))
    op.drop_column('chat_sessions', 'session_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('session_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('chat_sessions', 'conversation_id')
    # ### end Alembic commands ###
