"""add_agent_types_table

Revision ID: f5291c6257fc
Revises: 8e723b2e9e24
Create Date: 2025-07-24 11:19:58.801772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5291c6257fc'
down_revision: Union[str, None] = '8e723b2e9e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_types',
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.Enum('REGULAR', 'REACT', name='agent_type_enum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_types')
    # ### end Alembic commands ###
