"""removed unnecessary enum

Revision ID: f68eca5850f7
Revises: 6e89f43fd868
Create Date: 2025-06-11 09:27:44.211278

"""

from typing import Sequence, Union

# No operations needed for this migration

# revision identifiers, used by Alembic.
revision: str = "f68eca5850f7"
down_revision: Union[str, None] = "6e89f43fd868"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
