"""update_agent_foreign_key_to_cascade_delete

Revision ID: f8715b450aec
Revises: 2b75adb4d75d
Create Date: 2025-09-26 13:07:59.631208

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f8715b450aec'
down_revision: Union[str, None] = '2b75adb4d75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_sessions_agent_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'virtual_agent_configs', ['agent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(
        op.f('chat_sessions_agent_id_fkey'),
        'chat_sessions',
        'virtual_agent_configs',
        ['agent_id'],
        ['id']
    )
    # ### end Alembic commands ###
