"""create_chat_sessions_table

Revision ID: ffa2dde7aae5
Revises: faafd4ce8f16
Create Date: 2025-06-03 13:31:03.208001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa2dde7aae5'
down_revision: Union[str, None] = 'faafd4ce8f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('session_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_history', sa.Column('agent_id', sa.String(length=255), nullable=True))
    op.drop_column('chat_history', 'virtual_assistant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('virtual_assistant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('chat_history', 'agent_id')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
